[package]
name = "todo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vizia.workspace = true

[lints]
workspace = true
